name: Publish package
on:
  release:
    types: [created]
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip3 install --upgrade build

    - name: Build Python package
      run: python3 -m build --sdist --wheel --outdir dist/ .

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
